<?php

return [
    'technologies' => [
        'frontend' => [
            'HTML',
            'Angular',
            'Vue.js',
            'React',
        ],
        'backend' => [
            'PHP',
            'Laravel',
            'Symfony',
            'Node.js',
            'Express.js',
            'Django',
            'Flask',
            'Ruby on Rails',
            'Spring',
            'ASP.NET',
            'ASP.NET Core',
            'Django',
            'Flask',
            'Ruby on Rails',
            'Spring',
            'ASP.NET',
            'ASP.NET Core',
        ],
        'database' => [
            'MySQL',
            'PostgreSQL',
            'MongoDB',
            'Redis',
            'MariaDB',
            'SQLite',
            'Oracle',
            'Elasticsearch',
            'Cassandra',
            'Couchbase',
            'DynamoDB',
            'Firebase',
            'Neo4j',
            'CouchDB',
            'RethinkDB',
            'Memcached',
            'Couchbase',
            'DynamoDB',
            'Firebase',
            'Neo4j',
            'CouchDB',
            'RethinkDB',
            'Memcached',
        ],
        'other' => [
            'Docker',
            'Kubernetes',
            'AWS',
            'Azure',
            'Google Cloud',
            'Heroku',
            'DigitalOcean',
            'Netlify',
            'Vercel',
            'Firebase',
            'Git',
            'GitHub',
            'GitLab',
            'Bitbucket',
            'Jenkins',
            'Travis CI',
            'CircleCI',
            'Codeship',
            'TeamCity',
            'Bamboo',
            'Jira',
            'Trello',
            'Asana',
            'Slack',
            'Discord',
            'Zoom',
            'Google Meet',
            'Microsoft Teams',
            'Skype',
            'Notion',
            'Confluence',
            'Google Docs',
            'Google Sheets',
            'Google Slides',
            'Microsoft Word',
            'Microsoft Excel',
            'Microsoft PowerPoint',
            'Google Drive',
            'Dropbox',
            'OneDrive',
            'iCloud',
            'Google Analytics',
            'Google Tag Manager',
            'Google Search Console',
            'Hotjar',
            'Heap',
            'Amplitude',
            'Mixpanel',
            'Segment',
            'Optimizely',
            'VWO',
            'Crazy Egg',
            'FullStory',
            'Inspectlet',
            'Mouseflow',
            'Hotjar',
            'Heap',
            'Amplitude',
            'Mixpanel',
            'Segment',
            'Optimizely',
            'VWO',
            'Crazy Egg',
            'FullStory',
            'Inspectlet',
            'Mouseflow',
            'Hotjar',
            'Heap',
            'Amplitude',
            'Mixpanel',
            'Segment',
            'Optimizely',
            'VWO',
            'Crazy Egg',
            'FullStory',
            'Inspectlet',
            'Mouseflow',
            'Hotjar',
            'Heap',
            'Amplitude',
            'Mixpanel',
            'Segment',
            'Optimizely',
            'VWO',
            'Crazy Egg',
            'FullStory',
            'Inspectlet',
            'Mouseflow',
            'Hotjar',
            'Heap',
            'Amplitude',
            'Mixpanel',
            'Segment',
            'Optimizely',
            'VWO',
            'Crazy Egg',
            'FullStory',
            'Inspectlet',
            'Mouseflow',
            'Hotjar',
            'Heap',
            'Amplitude',
            'Mixpanel',
            'Segment',
            'Optimizely',
            'VWO',
            'Crazy Egg',
            'FullStory',
            'Inspectlet',
            'Mouseflow',
            'Hotjar',
            'Heap',
            'Amplitude',
            'Mixpanel',
            'Segment',
            'Optimizely',
            'VWO',
            'Crazy Egg',
            'FullStory',
            'Inspectlet',
            'Mouseflow',
            'Hotjar',
            'Heap',
            'Amplitude',
        ]
    ]
];
